yolo:
  # Jaecheol YOLO / RT-DETR baseline:
  train:
    imgsz: 640
    mosaic: 1.0
    degrees: 180.0
    flipud: 0.5
    fliplr: 0.5
    hsv_h: 0.1
    hsv_s: 0.7
    hsv_v: 0.4
    scale: 0.3
    translate: 0.1
    copy_paste: 0.3
  val:
    imgsz: 640
